### PR TITLE
fix: 修改icon onload没有执行问题

### PR DESCRIPTION
**Pull request by dzlhk**

### CODE REVIEW

**Comment by liujuping** [comment]
签一下 CLA

**Comment by dzlhk** [comment]
已经签了

**Comment by dzlhk** [comment]
https://github.com/alibaba/lowcode-engine/issues/954

**Comment by dzlhk** [comment]
https://github.com/alibaba/lowcode-engine/issues/954

**Comment by dzlhk** [comment]
https://github.com/alibaba/lowcode-engine/issues/954

**Comment by dzlhk** [comment]
这是修改的问题：https://github.com/alibaba/lowcode-engine/issues/954

**Comment by JackLian** [comment]
换到#18

**Pull request closed without merging**
